# Generated by Django 5.2.4 on 2025-07-05 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_aerolinea', '0001_create_model_avion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('fecha_salida', models.DateTimeField()),
                ('fecha_llegada', models.DateTimeField()),
                ('duracion', models.DurationField()),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('cancelado', 'Cancelado'), ('en curso', 'En curso'), ('finalizado', 'Finalizado')], max_length=20)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
