# Generated by Django 5.2.4 on 2025-07-05 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_aerolinea', '0002_create_model_vuelo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('tipo_documento', models.CharField(choices=[('dni', 'DNI'), ('pasaporte', 'Pasaporte'), ('otro', 'Otro')], max_length=20)),
                ('numero_documento', models.CharField(max_length=20, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
