# Generated by Django 5.2.4 on 2025-07-05 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_aerolinea', '0005_create_model_reserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barra', models.CharField(max_length=100, unique=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('emitido', 'Emitido'), ('cancelado', 'Cancelado'), ('usado', 'Usado')], default='emitido', max_length=20)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boleto', to='gestion_aerolinea.reserva')),
            ],
        ),
    ]
