# Generated by Django 5.2.4 on 2025-08-05 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_aerolinea', '0006_create_model_boleto'),
    ]

    operations = [
        migrations.AddField(
            model_name='vuelo',
            name='avion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_aerolinea.avion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='duracion',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
