# Generated by Django 5.2.4 on 2025-08-05 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_aerolinea', '0007_vuelo_avion_alter_vuelo_duracion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='usuario_reserva',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reservas_creadas', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
