# Generated by Django 5.2.4 on 2025-08-06 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_aerolinea', '0009_pasajero_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asiento',
            name='columna',
            field=models.IntegerField(),
        ),
    ]
