# Generated by Django 5.2.4 on 2025-08-07 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_aerolinea', '0010_alter_asiento_columna'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asiento',
            options={'ordering': ['fila', 'columna']},
        ),
        migrations.AddConstraint(
            model_name='asiento',
            constraint=models.UniqueConstraint(fields=('avion', 'fila', 'columna'), name='unico_asiento'),
        ),
    ]
