# Generated by Django 5.2.4 on 2025-08-13 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_aerolinea', '0011_cambios_en_Asiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avion',
            name='capacidad',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='asiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='gestion_aerolinea.asiento'),
        ),
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together={('vuelo', 'asiento')},
        ),
    ]
