# Generated by Django 5.2.4 on 2025-08-14 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_aerolinea', '0012_alter_avion_capacidad_alter_reserva_asiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vuelo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='vuelos_imagenes/'),
        ),
    ]
